# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Projects\btp7\SHAD\gui\select.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(1095, 712)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setAutoFillBackground(False)
        mainWindow.setStyleSheet("background: rgb(43, 46, 59);\n"
"")
        self.landing = QtWidgets.QWidget(mainWindow)
        self.landing.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.landing.setStyleSheet("QWidget#landing{\n"
"background: rgb(43, 46, 59);\n"
"}")
        self.landing.setObjectName("landing")
        self.pushButton = QtWidgets.QPushButton(self.landing)
        self.pushButton.setGeometry(QtCore.QRect(230, 590, 300, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(300, 60))
        self.pushButton.setBaseSize(QtCore.QSize(100, 100))
        self.pushButton.setStyleSheet(":enabled {\n"
"border-radius: 0px;\n"
"font-family: Courier New;\n"
"color: #ffffff;\n"
"font-size: 14pt;\n"
"background: transparent;\n"
"padding: 10pt 20pt 10pt 20pt;\n"
"border: 5px solid #ffffff;\n"
"text-decoration: none;\n"
"}\n"
":hover {\n"
"background: white;\n"
"color: rgb(43, 46, 59);\n"
"border: 0px;\n"
"}")
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.landing)
        self.label.setGeometry(QtCore.QRect(630, 230, 55, 16))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.landing)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 450, 300, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(300, 60))
        self.pushButton_2.setBaseSize(QtCore.QSize(100, 100))
        self.pushButton_2.setStyleSheet(":enabled {\n"
"border-radius: 0px;\n"
"font-family: Courier New;\n"
"color: #ffffff;\n"
"font-size: 14pt;\n"
"background: transparent;\n"
"padding: 10pt 20pt 10pt 20pt;\n"
"border: 5px solid #ffffff;\n"
"text-decoration: none;\n"
"}\n"
":hover {\n"
"background: white;\n"
"color: rgb(43, 46, 59);\n"
"border: 0px;\n"
"}")
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        mainWindow.setCentralWidget(self.landing)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.pushButton.setText(_translate("mainWindow", "Select a video"))
        self.label.setText(_translate("mainWindow", "TextLabel"))
        self.pushButton_2.setText(_translate("mainWindow", "Back"))
